site_name: ⚜️ Clientele
site_url: https://phalt.github.io/clientele/
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_name: phalt/clientele
repo_url: https://github.com/phalt/clientele
nav:
  - Home: index.md
  - Getting Started:
    - Install: install.md
  - API Client guide:
    - Overview: api-overview.md
    - Configuration: api-configuration.md
    - Async Support: api-async.md
    - Authentication: api-authentication.md
    - Exception Handling: exceptions.md
    - Testing: testing.md
  - Client Scaffolder:
    - Usage & CLI: openapi-cli.md
    - Regeneration: openapi-regeneration.md
    - Barebones Configuration: openapi-configuration.md
    - Barebones authentication: openapi-authentication.md
    - Generated Client Tour: examples.md
    - Compatibility & Limitations: compatibility.md
    - References in OpenAPI: references.md
  - API Server Integrations:
    - FastAPI: server-fastapi.md
    - Django REST Framework: server-drf.md
    - Django Ninja: server-django-ninja.md
  - API Explorer:
    - Overview: explore.md
  - About:
    - Background: design.md
    - Change Log: CHANGELOG.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - codehilite
