site_name: ⚜️ Clientele
site_url: https://phalt.github.io/clientele/
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
repo_name: phalt/clientele
repo_url: https://github.com/phalt/clientele
nav:
  - Home: index.md
  - Getting Started:
    - Install: install.md
    - Usage & CLI: usage.md
  - Framework Guides:
    - FastAPI: framework-fastapi.md
    - Django REST Framework: framework-drf.md
    - Django Ninja: framework-django-ninja.md
  - Documentation:
    - Configuration: configuration.md
    - Client Examples: examples.md
    - Testing: testing.md
    - Explorer Mode: explore.md
    - Compatibility & Limitations: compatibility.md
    - Complex Schemas: complex_schemas.md
    - References in OpenAPI: references.md
  - About:
    - Design Philosophy: design.md
    - Change Log: CHANGELOG.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - codehilite
