site_name: ⚜️ Clientele
site_url: https://phalt.github.io/clientele/
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_name: phalt/clientele
repo_url: https://github.com/phalt/clientele
nav:
  - Home: index.md
  - Getting Started:
    - Install: install.md
    - Usage & CLI: usage.md
  - Framework Guides:
    - FastAPI: framework-fastapi.md
    - Django REST Framework: framework-drf.md
    - Django Ninja: framework-django-ninja.md
    - Decorator Client: framework-decorator-client.md
  - Documentation:
    - Configuration: configuration.md
    - Regeneration: regeneration.md
    - Authentication: authentication.md
    - Exception Handling: exceptions.md
    - Generated Client Tour: examples.md
    - Testing: testing.md
    - Explorer Mode: explore.md
    - Compatibility & Limitations: compatibility.md
    - Complex Schemas: complex_schemas.md
    - References in OpenAPI: references.md
  - About:
    - Design Philosophy: design.md
    - Change Log: CHANGELOG.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - codehilite
