site_name: ⚜️ Clientele
site_url: https://phalt.github.io/clientele/
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
repo_name: phalt/clientele
repo_url: https://github.com/phalt/clientele
nav:
  - Home: index.md
  - Install: install.md
  - Use: usage.md
  - Design: design.md
  - Client Example: examples.md
  - Complex Schemas: complex_schemas.md
  - Testing: testing.md
  - Compatibility: compatibility.md
  - Change log: CHANGELOG.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - codehilite
