site_name: Clientele
site_url: https://docs.clientele.dev
theme:
  name: material
  favicon: favicon.png
  logo: favicon.png
  features:
    - navigation.tabs
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_name: phalt/clientele
repo_url: https://github.com/phalt/clientele
nav:
  - âšœï¸ Home: index.md
  - ğŸš€ Install:
    - Install: install.md
  - ğŸ“• Documentation:
    - Documentation: api-overview.md
    - ğŸª Examples: api-examples.md
    - âš™ï¸ Configuration: api-configuration.md
    - ğŸ”€ Async Support: api-async.md
    - ğŸ” Authentication: api-authentication.md
    - ğŸ”Œ HTTP Backends: api-http-backends.md
    - ğŸ’¾ Caching: api-cache.md
    - ğŸŒŠ Streaming: api-stream.md
    - ğŸ§¬ GraphQL: api-graphql.md
    - ğŸš¨ Exception Handling: api-exceptions.md
    - ğŸ”„ Retries: api-retries.md
    - ğŸªµ Logging: api-logging.md
    - ğŸ§ª Testing: api-testing.md
    - ğŸ¯ Direct requests: api-direct-requests.md
    - ğŸ¥§ Mypy support: mypy.md
  - ğŸ“Ÿ Command line tools:
    - ğŸ—ï¸ Client creator: openapi-cli.md
  - âš¡ï¸ API Server Integrations:
    - âš¡ï¸ FastAPI: server-fastapi.md
    - ğŸ¦„ Django REST Framework: server-drf.md
    - ğŸ¥· Django Ninja: server-django-ninja.md
  - ğŸ“ Change Log: CHANGELOG.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - codehilite
